const clean = (value) => String(value || "").replace(/\s+/g, " ").trim();
const key = (value) => clean(value).toLowerCase();

const ALIASES = new Map(
  [
    ["Cal Poly Humboldt", "California State Polytechnic University-Humboldt"],
    ["Columbia University", "Columbia University in the City of New York"],
    ["Baruch College", "CUNY Bernard M Baruch College"],
    ["Bronx Community College", "CUNY Bronx Community College"],
    ["Brooklyn College", "CUNY Brooklyn College"],
    ["College of Staten Island", "College of Staten Island CUNY"],
    ["City College", "CUNY City College"],
    ["Hunter College", "CUNY Hunter College"],
    ["Queens College", "CUNY Queens College"],
    ["East Stroudsburg University", "East Stroudsburg University of Pennsylvania"],
    ["Franklin and Marshall College", "Franklin & Marshall College"],
    ["Borough OF Manhattan", "CUNY Borough of Manhattan Community College"],
    ["Graduate Center", "CUNY Graduate School and University Center"],
    ["John Jay College", "CUNY John Jay College of Criminal Justice"],
    ["School OF Professional Studies", "CUNY School of Professional Studies"],
    ["PennWest", "Pennsylvania Western University"],
    ["Lassen College", "Lassen Community College"],
    ["Marist College", "Marist University"],
    ["San Francisco CCD", "City College of San Francisco"],
    ["The Citadel", "Citadel Military College of South Carolina"],
    ["UC San Diego", "University of California-San Diego"],
    ["UNC Greensboro", "University of North Carolina at Greensboro"],
    ["UNC Pembroke", "University of North Carolina at Pembroke"],
    ["UNC-Chapel Hill", "University of North Carolina at Chapel Hill"],
    ["University of Nebraska Omaha", "University of Nebraska at Omaha"],
    ["Yuba CCD", "Yuba College"],
    ["SUNY Cayuga", "Cayuga County Community College"],
    ["SUNY Empire State College", "Empire State University"],
    ["SUNY Fredonia", "SUNY at Fredonia"],
    ["SUNY Herkimer", "Herkimer County Community College"],
    ["SUNY New Paltz", "State University of New York at New Paltz"],
    ["SUNY Niagara", "Niagara County Community College"],
    ["SUNY Potsdam", "SUNY College at Potsdam"],
    ["SUNY Purchase", "SUNY at Purchase College"],
    ["California State University, Stanislaus invites applications for a full-time", "California State University-Stanislaus"],
    ["California State University, Stanislaus invites applications for a tenure-track Assistant Professor specializing in Writing Studies. We seek a committed teacher-scholar who is excited to contribute to a department that values innovation", "California State University-Stanislaus"],
    ["California State University, Stanislaus One University Circle Turlock", "California State University-Stanislaus"],
    ["CT State Asnuntuck", "Connecticut State Community College"],
    ["CT State Capital", "Connecticut State Community College"],
    ["CT State CC", "Connecticut State Community College"],
    ["CT State Community College", "Connecticut State Community College"],
    ["CT State Gateway", "Connecticut State Community College"],
    ["CT State Housatonic", "Connecticut State Community College"],
    ["CT State Manchester", "Connecticut State Community College"],
    ["CT State Naugatuck Valley", "Connecticut State Community College"],
    ["CT State Norwalk", "Connecticut State Community College"],
    ["CT State Quinebaug Valley", "Connecticut State Community College"],
    ["CT State Three Rivers", "Connecticut State Community College"],
    ["CT State Tunxis", "Connecticut State Community College"],
    ["Minnesota State (Alexandria)", "Alexandria Technical & Community College"],
    ["Minnesota State (Anoka)", "Anoka Technical College"],
    ["Minnesota State (Arcc Cambridge Campus)", "Anoka-Ramsey Community College"],
    ["Minnesota State (Austin)", "Riverland Community College"],
    ["Minnesota State (Bloomington)", "Normandale Community College"],
    ["Minnesota State (Brooklyn Park)", "North Hennepin Community College"],
    ["Minnesota State (Cloquet)", "Fond du Lac Tribal and Community College"],
    ["Minnesota State (East Grand Forks)", "Northland Community and Technical College"],
    ["Minnesota State (Henn Brooklyn Park Campus)", "Hennepin Technical College"],
    ["Minnesota State (Hutchinson)", "Ridgewater College"],
    ["Minnesota State (Inver Grove Heights)", "Inver Hills Community College"],
    ["Minnesota State (Msse Winona Campus)", "Minnesota State College Southeast"],
    ["Minnesota State (Msta Moorhead Campus)", "Minnesota State University Moorhead"],
    ["Minnesota State (Msta Wadena Campus)", "Minnesota State Community and Technical College"],
    ["Minnesota State (Mwst Jackson Campus)", "Minnesota West Community and Technical College"],
    ["Minnesota State (Mwst Pipestone Campus)", "Minnesota West Community and Technical College"],
    ["Minnesota State (Nlnd Thief River Falls Campus)", "Northland Community and Technical College"],
    ["Minnesota State (Norm Bloomington Campus)", "Normandale Community College"],
    ["Minnesota State (Rivr Owatonna Campus)", "Riverland Community College"],
    ["Minnesota State (Rosemount)", "Dakota County Technical College"],
    ["Minnesota State (Staples)", "Central Lakes College-Brainerd"],
    ["Arizona State University", "Arizona State University Campus Immersion"],
    ["Antelope Valley CCD", "Antelope Valley Community College District"],
    ["California Polytechnic State University, San Luis Obispo", "California Polytechnic State University-San Luis Obispo"],
    ["California State University, Bakersfield", "California State University-Bakersfield"],
    ["California State University, Stanislaus", "California State University-Stanislaus"],
    ["California State University, San Bernardino", "California State University-San Bernardino"],
    ["California State Polytechnic University, Pomona", "California State Polytechnic University-Pomona"],
    ["California State University, Chico", "California State University-Chico"],
    ["California State University, Fresno", "California State University-Fresno"],
    ["California State University, Fullerton", "California State University-Fullerton"],
    ["California State University, East Bay", "California State University-East Bay"],
    ["California State University, Long Beach", "California State University-Long Beach"],
    ["California State University, Los Angeles", "California State University-Los Angeles"],
    ["California State University, Northridge", "California State University-Northridge"],
    ["California State University, Sacramento", "California State University-Sacramento"],
    ["El Camino CCD", "El Camino Community College District"],
    ["Colorado State University", "Colorado State University-Fort Collins"],
    ["SUNY Dutchess Community College", "Dutchess Community College"],
    ["SUNY Erie Community College", "Erie Community College"],
    ["SUNY Fashion Institute of Technology", "Fashion Institute of Technology"],
    ["SUNY Finger Lakes Community College", "Finger Lakes Community College"],
    ["Farmingdale State College (SUNY)", "Farmingdale State College"],
    ["University at Albany (SUNY)", "University at Albany"],
    ["Binghamton University (SUNY)", "Binghamton University"],
    ["University at Buffalo (SUNY)", "University at Buffalo"],
    ["Stony Brook University (SUNY)", "Stony Brook University"],
    ["Cheyney University", "Cheyney University of Pennsylvania"],
    ["California State University San Marcos", "California State University-San Marcos"],
    ["California State University, Monterey Bay", "California State University-Monterey Bay"],
    ["California State University Channel Islands", "California State University-Channel Islands"],
    ["Commonwealth University", "Commonwealth University of Pennsylvania"],
    ["SUNY Genesee Community College", "Genesee Community College"],
    ["SUNY Jamestown Community College", "Jamestown Community College"],
    ["SUNY Schenectady County Community College", "Schenectady County Community College"],
    ["UNC School of the Arts", "University of North Carolina School of the Arts"],
  ].map(([alias, canonical]) => [key(alias), canonical])
);

export function canonicalInstitutionName(name) {
  const value = clean(name);
  return ALIASES.get(key(value)) || value;
}

export function isInstitutionAlias(name) {
  return ALIASES.has(key(name));
}
